Revert "ANDROID: userfaultfd: allow SPF for UFFD_FEATURE_SIGBUS on private+anon"
This reverts commit 9b613572d6246da9b616f34e4a0e0b5ac74b2dd0 due to
build error
./include/linux/rcupdate.h:400:9: error: dereferencing pointer to
                               incomplete type ‘struct userfaultfd_ctx’

Signed-off-by: Jeevaka Prabu Badrappan <jeevaka.badrappan@intel.com>